### ISSUE TITLE
Dostop do baze

### ISSUE THREAD

**Issue by jaanos** [vkriznar/gaming-forum#3]
Opažam, da imaš @BumbarG v datoteki `auth_public.py` svoje geslo, ki je tako za vekomaj objavljeno na internetu in zato svetujem, da ga zamenjaš.

Datoteka `auth_public.py` je namenjena prijavi z uporabnikom `javnost`, tako da bo lahko kdorkoli uporabljal vajino aplikacijo. Za namene ustvarjanja tabel in uvoza podatkov uporabita datoteko `auth.py` - ta bo vsebovala geslo vsakega od vaju in zato ne sodi na repozitorij, tako da dodajta vrstico `auth.py` v `.gitignore`, da je ne bosta dodala po nesreči.

Seveda bo potrebno nastaviti tudi ustrezne pravice - poglejta si pdurcik/Baza-clanstva-RDR#3.

**Comment by BumbarG** [comment]
Hvala! Sem popravil v commitu 364cf6fabb4a84c8f9be5beb62ae0848a7c032cd(odstranil geslo) in commitu f4334c64a71152c1c915f1fe76fed8b523d9932f(dodal pravice).
