### ISSUE TITLE
Ustvarjanje tabel in uvoz podatkov

### ISSUE THREAD

**Issue by jaanos** [vkriznar/gaming-forum#4]
Nikjer ne vidim skripte ali datoteke s stavki SQL za ustvarjanje vajinih tabel. Svetujem, da tudi to vključita na repozitorij, saj bo morda kdaj potrebno na novo ustvariti tabele, in v tem primeru bo to prišlo prav (ne pozabita na pravice - glejta #3).

V `Podatki_in_generiranje/OPB_data.py` pripravita podatke za uvoz, pri tem pa bereta iz datoteke izven repozitorija:

https://github.com/vkriznar/gaming-forum/blob/9c9515d36eb0a692a5cb74667218f7cbb69e4b50/Podatki_in_generiranje/OPB_data.py#L28-L31

Svetujem, da te datoteke naložita na repozitorij, nanje se pa sklicujeta z relativnimi potmi (npr. `podatki/test.csv`) - sicer bo skripta delovala samo na enem računalniku.

Pri pripravi stavkov SQL pa naredita npr. to:

https://github.com/vkriznar/gaming-forum/blob/9c9515d36eb0a692a5cb74667218f7cbb69e4b50/Podatki_in_generiranje/OPB_data.py#L39

Kljub temu, da se pri izvajanju skripte stavek samo zapiše v datoteko, pa lahko pri izvajanju vseeno pride do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/) (pravzaprav je to pri vstavljanju preko spletnega vmesnika še bolj nevarno, saj ta dejansko omogoča izvedbo več stavkov hkrati). Zato svetujem, da se v skripti neposredno povežeta na bazo s `psycopg2` in stavek izvedeta z ustrezno uporabo metode `execute` (glejta tjasabajc/Recepti#2).

**Comment by jaanos** [comment]
Še to: v zgornji poizvedbi se dvakrat pojavi stolpec `id` - najbrž ga bo potrebno enkrat zamenjati z drugim stolpcem.

**Comment by BumbarG** [comment]
@jaanos Se mi zdi, da sem z oznacenim commitom to sedaj popravil. Imam pa vprašanje glede Constrainta, ki sem ga hotel uvesti v tabeli (gaming-forum/Podatki_in_generiranje/tabele.sql) 'Igralec'. Problem je sledeč: imam tabele ima_vlogo, kjer navedem, katere možne vloge imajo posamezne igre in bi rad, ko bo uporabnik izpolnjeval obrazec za 'Igralec' dodal constraint, ki preveri, če ima igra, ki jo je izbral izbrano vlogo. To sem probal storiti tako, da preverim, če je primary key (igra vloga) enak null, ampak ni delovalo (CONSTRAINT igra_vloga CHECK(ima_vlogo(igra, vloga) IS NOT NULL)). Imate kakšen predlog?

**Comment by jaanos** [comment]
To se reši s tujimi ključi. Tabela `na_platformi` naj ima glavni ključ iz obeh stolpcev (tako kot `ima_vlogo`), tabeli `igralec` pa dodajta tuja ključa - `igra` in `vloga` naj bosta referenca na `ima_vlogo`, `igra` in `platforma` pa na `na_platformi`.
